const movieList = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/2v3pC01rf0uXnECOM94pjfqk1TY.jpg",
      genre_ids: [80, 18, 53, 28],
      id: 75780,
      original_language: "en",
      original_title: "Jack Reacher",
      overview:
        "One morning in an ordinary town, five people are shot dead in a seemingly random attack. All evidence points to a single suspect: an ex-military sniper who is quickly brought into custody. The interrogation yields one written note: 'Get Jack Reacher!'. Reacher, an enigmatic ex-Army investigator, believes the authorities have the right man but agrees to help the sniper's defense attorney. However, the more Reacher delves into the case, the less clear-cut it appears. So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.",
      popularity: 3.84,
      poster_path: "/gLv55839pz4lhyKGRaJKbty41yq.jpg",
      release_date: "2012-12-20",
      title: "Jack Reacher",
      video: false,
      vote_average: 6.638,
      vote_count: 7123,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 1045592,
      original_language: "en",
      original_title: "Jack Reacher: When the Man Comes Around",
      overview:
        "Cast and crew speak on adapting One Shot as the first Jack Reacher film, casting Tom Cruise, earning Lee Child's blessing, additional character qualities and the performances that shape them, Lee Child's cameo in the film, and shooting the film's climax.",
      popularity: 0.11,
      poster_path: "/tcOPca5Ook6aR9mehrnxD9kfk7m.jpg",
      release_date: "2013-05-07",
      title: "Jack Reacher: When the Man Comes Around",
      video: false,
      vote_average: 7.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/ww1eIoywghjoMzRLRIcbJLuKnJH.jpg",
      genre_ids: [28, 53],
      id: 343611,
      original_language: "en",
      original_title: "Jack Reacher: Never Go Back",
      overview:
        "Years after resigning command of an elite military police unit, the nomadic, righter-of-wrongs Reacher is drawn back into the life he left behind when his friend and successor, Major Susan Turner is framed for espionage. Reacher will stop at nothing to prove her innocence and to expose the real perpetrators behind the killings of his former soldiers.",
      popularity: 3.548,
      poster_path: "/cOg3UT2NYWHZxp41vpxAnVCOC4M.jpg",
      release_date: "2016-10-19",
      title: "Jack Reacher: Never Go Back",
      video: false,
      vote_average: 5.991,
      vote_count: 4962,
    },
  ],
  total_pages: 1,
  total_results: 3,
};
const movieItem = {
  adult: false,
  backdrop_path: "/ww1eIoywghjoMzRLRIcbJLuKnJH.jpg",
  belongs_to_collection: {
    id: 403374,
    name: "Jack Reacher Collection",
    poster_path: "/qtafXiYDUMKxzsssU41qWey5oiT.jpg",
    backdrop_path: "/vViRXFnSyGJ2fzMbcc5sqTKswcd.jpg",
  },
  budget: 60000000,
  genres: [
    { id: 28, name: "Action" },
    { id: 53, name: "Thriller" },
  ],
  homepage: "https://skydance.com/film/jack-reacher-never-go-back/",
  id: 343611,
  imdb_id: "tt3393786",
  origin_country: ["US"],
  original_language: "en",
  original_title: "Jack Reacher: Never Go Back",
  overview:
    "Years after resigning command of an elite military police unit, the nomadic, righter-of-wrongs Reacher is drawn back into the life he left behind when his friend and successor, Major Susan Turner is framed for espionage. Reacher will stop at nothing to prove her innocence and to expose the real perpetrators behind the killings of his former soldiers.",
  popularity: 3.548,
  poster_path: "/cOg3UT2NYWHZxp41vpxAnVCOC4M.jpg",
  production_companies: [
    {
      id: 82819,
      logo_path: "/gXfFl9pRPaoaq14jybEn1pHeldr.png",
      name: "Skydance Media",
      origin_country: "US",
    },
    { id: 83645, logo_path: null, name: "Huahua Media", origin_country: "CN" },
    {
      id: 3407,
      logo_path: "/iVMjKOFyRvm9PW45lW1wW6TSvnj.png",
      name: "Shanghai Film Group",
      origin_country: "CN",
    },
    {
      id: 21777,
      logo_path: null,
      name: "TC Productions",
      origin_country: "US",
    },
    {
      id: 4,
      logo_path: "/gz66EfNoYPqHTYI4q9UEN4CbHRc.png",
      name: "Paramount Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "CN", name: "China" },
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2016-10-19",
  revenue: 162100000,
  runtime: 118,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "Never give in. Never give up. Never go back.",
  title: "Jack Reacher: Never Go Back",
  video: false,
  vote_average: 5.991,
  vote_count: 4962,
};
module.exports = {
  movieList,
  movieItem,
};
