export const moviePage = {
  adult: false,
  backdrop_path: "/htmYEfH7TQgzsXHCnNXxmoYKQtL.jpg",
  belongs_to_collection: {
    id: 1241,
    name: "Harry Potter Collection",
    poster_path: "/s4hXqX1VyWMc2ctJRuNBDB7YNJ3.jpg",
    backdrop_path: "/kmEsQL2vOTA0jnM28fXS45Ky8kX.jpg",
  },
  budget: 130000000,
  genres: [
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 14,
      name: "Fantasy",
    },
  ],
  homepage:
    "https://www.warnerbros.com/movies/harry-potter-and-prisoner-azkaban/",
  id: 673,
  imdb_id: "tt0304141",
  origin_country: ["GB"],
  original_language: "en",
  original_title: "Harry Potter and the Prisoner of Azkaban",
  overview:
    "Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.",
  popularity: 4.355,
  poster_path: "/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
  production_companies: [
    {
      id: 174,
      logo_path: "/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png",
      name: "Warner Bros. Pictures",
      origin_country: "US",
    },
    {
      id: 436,
      logo_path: "/A7WCkG3F0NFvjGCwUnclpGdIu9E.png",
      name: "1492 Pictures",
      origin_country: "US",
    },
    {
      id: 437,
      logo_path: "/nu20mtwbEIhUNnQ5NXVhHsNknZj.png",
      name: "Heyday Films",
      origin_country: "GB",
    },
    {
      id: 19092,
      logo_path: null,
      name: "P of A Productions Limited",
      origin_country: "",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "GB",
      name: "United Kingdom",
    },
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2004-05-31",
  revenue: 789804554,
  runtime: 141,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Something wicked this way comes.",
  title: "Harry Potter and the Prisoner of Azkaban",
  video: false,
  vote_average: 8,
  vote_count: 21965,
};
export const movieSearch = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/bfh9Z3Ghz4FOJAfLOAhmc3ccnHU.jpg",
      genre_ids: [12, 14],
      id: 671,
      original_language: "en",
      original_title: "Harry Potter and the Philosopher's Stone",
      overview:
        "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
      popularity: 3.626,
      poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
      release_date: "2001-11-16",
      title: "Harry Potter and the Philosopher's Stone",
      video: false,
      vote_average: 7.902,
      vote_count: 28024,
    },
    {
      adult: false,
      backdrop_path: "/htmYEfH7TQgzsXHCnNXxmoYKQtL.jpg",
      genre_ids: [12, 14],
      id: 673,
      original_language: "en",
      original_title: "Harry Potter and the Prisoner of Azkaban",
      overview:
        "Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.",
      popularity: 4.355,
      poster_path: "/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
      release_date: "2004-05-31",
      title: "Harry Potter and the Prisoner of Azkaban",
      video: false,
      vote_average: 8,
      vote_count: 21965,
    },
    {
      adult: false,
      backdrop_path: "/yHzyPJrVqlTySQ9mc379yxrLBYQ.jpg",
      genre_ids: [12, 14],
      id: 672,
      original_language: "en",
      original_title: "Harry Potter and the Chamber of Secrets",
      overview:
        "Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
      popularity: 4.596,
      poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
      release_date: "2002-11-13",
      title: "Harry Potter and the Chamber of Secrets",
      video: false,
      vote_average: 7.709,
      vote_count: 22383,
    },
    {
      adult: false,
      backdrop_path: "/5rrGVmRUuCKVbqUu41XIWTXJmNA.jpg",
      genre_ids: [12, 14],
      id: 674,
      original_language: "en",
      original_title: "Harry Potter and the Goblet of Fire",
      overview:
        "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools—the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named.",
      popularity: 4.344,
      poster_path: "/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
      release_date: "2005-11-16",
      title: "Harry Potter and the Goblet of Fire",
      video: false,
      vote_average: 7.802,
      vote_count: 21045,
    },
    {
      adult: false,
      backdrop_path: "/82a7AGF081PzFfoM8GAVGMvZNYK.jpg",
      genre_ids: [12, 14],
      id: 675,
      original_language: "en",
      original_title: "Harry Potter and the Order of the Phoenix",
      overview:
        "Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students to defend themselves against the dark arts.",
      popularity: 4.347,
      poster_path: "/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg",
      release_date: "2007-07-08",
      title: "Harry Potter and the Order of the Phoenix",
      video: false,
      vote_average: 7.674,
      vote_count: 19763,
    },
    {
      adult: false,
      backdrop_path: "/g8dafKwLfaueQ5GK0qjKTkRCBAA.jpg",
      genre_ids: [99],
      id: 899082,
      original_language: "en",
      original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
      overview:
        "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
      popularity: 3.554,
      poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
      release_date: "2022-01-01",
      title: "Harry Potter 20th Anniversary: Return to Hogwarts",
      video: false,
      vote_average: 7.302,
      vote_count: 3389,
    },
    {
      adult: false,
      backdrop_path: "/n5A7brJCjejceZmHyujwUTVgQNC.jpg",
      genre_ids: [14, 12],
      id: 12445,
      original_language: "en",
      original_title: "Harry Potter and the Deathly Hallows: Part 2",
      overview:
        "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.",
      popularity: 4.103,
      poster_path: "/c54HpQmuwXjHq2C9wmoACjxoom3.jpg",
      release_date: "2011-07-12",
      title: "Harry Potter and the Deathly Hallows: Part 2",
      video: false,
      vote_average: 8.088,
      vote_count: 20885,
    },
    {
      adult: false,
      backdrop_path: "/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg",
      genre_ids: [12, 14],
      id: 12444,
      original_language: "en",
      original_title: "Harry Potter and the Deathly Hallows: Part 1",
      overview:
        "Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
      popularity: 4.394,
      poster_path: "/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
      release_date: "2010-11-17",
      title: "Harry Potter and the Deathly Hallows: Part 1",
      video: false,
      vote_average: 7.7,
      vote_count: 19365,
    },
    {
      adult: false,
      backdrop_path: "/4LOxoeZWt5wr9mooxEZRFK96lDd.jpg",
      genre_ids: [99],
      id: 483898,
      original_language: "en",
      original_title: "50 Greatest Harry Potter Moments",
      overview:
        "To mark the release two weeks ago of the eighth and final movie in the series, Robbie Coltrane narrates a countdown of the movie franchise's best moments. From Harry's first meeting with Ron and Hermione aboard the Hogwarts Express through to magical mysteries.",
      popularity: 3.533,
      poster_path: "/g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg",
      release_date: "2011-07-27",
      title: "50 Greatest Harry Potter Moments",
      video: false,
      vote_average: 7.5,
      vote_count: 130,
    },
    {
      adult: false,
      backdrop_path: "/mjCYpJXCBYDZgMr1U1KZcFgFDfC.jpg",
      genre_ids: [99],
      id: 482408,
      original_language: "en",
      original_title: "Harry Potter: A History Of Magic",
      overview:
        "A thrilling journey through legends, belief and folklore, this film goes behind the scenes with the British Library as they search to tell that story through objects in their collection, in an ambitious new exhibition: Harry Potter: A History Of Magic.  J.K. Rowling, who is lending unseen manuscripts, drawings and drafts from her private archives (which will sit alongside treasures from the British Library, as well as original drafts and drawings from Jim Kay) talks about some of the personal items she has lent to the exhibition and gives new insight into her writing, looking at some of the objects from the exhibition that have fired her imagination.",
      popularity: 3.148,
      poster_path: "/kkzDng2S8w2hT1gap7MdMdx7uUE.jpg",
      release_date: "2017-10-28",
      title: "Harry Potter: A History Of Magic",
      video: false,
      vote_average: 7.3,
      vote_count: 89,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 1082707,
      original_language: "en",
      original_title: "The Magic Touch of Harry Potter",
      overview:
        "A 2004 documentary on the first three “Harry Potter” films detailing the behind-the-scenes journey of making them.",
      popularity: 0.637,
      poster_path: "/gwFARNYf1Odv3E8ESVHyikXmMIY.jpg",
      release_date: "2004-06-11",
      title: "The Magic Touch of Harry Potter",
      video: false,
      vote_average: 7.4,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 10770],
      id: 918078,
      original_language: "en",
      original_title: "Daniel Radcliffe: Being Harry Potter",
      overview:
        "Made-for-television documentary about Daniel Radcliffe and his role as Harry Potter.",
      popularity: 0.78,
      poster_path: "/4keobTsQVrMS2JwE3TRod0SrYTD.jpg",
      release_date: "2012-10-10",
      title: "Daniel Radcliffe: Being Harry Potter",
      video: false,
      vote_average: 6.5,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 919590,
      original_language: "de",
      original_title:
        "Phantastische Harry Potter Momente - Das große SAT.1 Spezial",
      overview: "",
      popularity: 1.077,
      poster_path: "/1Ci05BbrRgc8qwKSvliJH6gqzol.jpg",
      release_date: "2021-10-31",
      title: "Phantastische Harry Potter Momente - Das große SAT.1 Spezial",
      video: false,
      vote_average: 6.8,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: "/zikoNIlodwkPhAU9iAwN17sOTrD.jpg",
      genre_ids: [99, 14],
      id: 1118680,
      original_language: "fr",
      original_title: "Harry Potter : les secrets du phénomène",
      overview:
        "Immerse yourself in the magic of Harry Potter by uncovering the secrets behind the global bestseller. Over 20 years later, the wizards of Hogwarts remain immensely popular among audiences, transcending generations. To grasp the reasons behind such success, this documentary will introduce you to the most extravagant fans who perpetuate the phenomenon.",
      popularity: 0.28,
      poster_path: "/7iJ20z09sZpbl0vgj4NIbnUDcfN.jpg",
      release_date: "2023-04-26",
      title: "Harry Potter : les secrets du phénomène",
      video: false,
      vote_average: 8.4,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
      genre_ids: [12, 14],
      id: 767,
      original_language: "en",
      original_title: "Harry Potter and the Half-Blood Prince",
      overview:
        "As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
      popularity: 4.357,
      poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
      release_date: "2009-07-15",
      title: "Harry Potter and the Half-Blood Prince",
      video: false,
      vote_average: 7.684,
      vote_count: 19752,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10751, 99, 10770],
      id: 116972,
      original_language: "en",
      original_title: "Discovering the Real World of Harry Potter",
      overview:
        "Explore the myths and legends that inhabit the real world of Harry Potter. Follow award-winning documentary filmmakers as they offer insights to witches, wizards, Greek gods, ancient Celts, ghosts, magical creatures, alchemy, and ancient spells. Narrated by British actor Hugh Laurie, this fascinating documentary brings new dimensions to the historical and scientific world behind the Harry Potter series.",
      popularity: 0.848,
      poster_path: "/yLpnOqKw3ZycFu8t5Gil1BqTbnB.jpg",
      release_date: "2001-12-10",
      title: "Discovering the Real World of Harry Potter",
      video: false,
      vote_average: 6.9,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 14],
      id: 1039274,
      original_language: "en",
      original_title: "Harry Potter: A Spirit Conspiracy?",
      overview:
        "The Occult Agenda documentary series is designed to awaken the church and non-believers alike to the spiritual warfare happening in the world today. Part I focuses on the Harry Potter phenomenon that has swept the world since author J.K. Rowling introduced her best-selling book series. But is Potter-mania merely the result of imaginative writing and clever marketing? Or could there be a hidden power behind the craze that has cast a spell on adults and children alike?",
      popularity: 0.425,
      poster_path: "/e8jvqpVbVeVlSOV216sOIZmykGA.jpg",
      release_date: "2005-09-22",
      title: "Harry Potter: A Spirit Conspiracy?",
      video: true,
      vote_average: 6.5,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 319391,
      original_language: "en",
      original_title: "J.K. Rowling and the Birth of Harry Potter",
      overview:
        "In this fascinating (unauthorized) biographical documentary, you'll get the inside scoop on the creative force behind one of the greatest publishing phenomena in the last 100 years -- J.K. Rowling, author of the Harry Potter series of books. Explore Rowling's meteoric rise from obscurity into the ranks of the world's richest women (via her books), and visit the people and places that played a significant role in her life.",
      popularity: 0.742,
      poster_path: "/hY6Ndq1O4JiEngZ7xIOtcLUCDTX.jpg",
      release_date: "2004-12-07",
      title: "J.K. Rowling and the Birth of Harry Potter",
      video: false,
      vote_average: 7.1,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 500008,
      original_language: "en",
      original_title: "Harry Potter: The Making of Diagon Alley",
      overview:
        "An inside look into the creation of Universal Studio's Diagon Alley attraction.",
      popularity: 0.57,
      poster_path: null,
      release_date: "2014-06-30",
      title: "Harry Potter: The Making of Diagon Alley",
      video: false,
      vote_average: 5.656,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 1111760,
      original_language: "de",
      original_title: "Schottland - Auf den Spuren von Harry Potter",
      overview: "",
      popularity: 0.035,
      poster_path: null,
      release_date: "",
      title: "Schottland - Auf den Spuren von Harry Potter",
      video: false,
      vote_average: 9.5,
      vote_count: 1,
    },
  ],
  total_pages: 2,
  total_results: 25,
};
